#!/bin/sh

set -eu

CC=${CC:-gcc}
MILONE_HOME=${MILONE_HOME:-"${HOME}/.milone"}
MILONE_RUNTIME="$MILONE_HOME/runtime"

$CC -std=gnu11 -g \
    -fsanitize=undefined \
    -Wall \
    -Wextra \
    -Wno-unused-but-set-parameter \
    -Wno-unused-but-set-variable \
    -Wno-unused-label \
    -Wno-unused-parameter \
    -Wno-unused-variable \
    $(pkg-config --cflags --libs gtk+-3.0) \
    -I$MILONE_RUNTIME \
    "$MILONE_RUNTIME/milone.c" \
    app_gtk.c \
    target/app_gtk.c \
    -o target/app \
    $(pkg-config --libs gtk+-3.0)
