#!/bin/sh

set -eu

CC=${CC:-gcc}
MILONE_HOME=${MILONE_HOME:-$HOME/.milone}
TARGET=$PWD/../target/LibHttpServer

milone build --target-dir "$TARGET" $PWD
mv -f "$TARGET/x86_64-unknown-linux-gnu-debug/LibHttpServer" "$TARGET/httpd"

echo "trace: Built. '$TARGET/httpd'" >&2
