int main();

int main() {
    int match_;
    char call_ = ((char)97);
    if (!(((call_ != 'a') == 1))) goto next_2;
    exit(1);
    match_ = 0;
    goto end_match_1;
next_2:;
    if (!(((call_ != 'a') == 0))) goto next_3;
    match_ = 0;
    goto end_match_1;
next_3:;
    exit(1);
end_match_1:;
    int match_1;
    char call_1 = ((char)0);
    if (!(((call_1 != '\0') == 1))) goto next_5;
    exit(1);
    match_1 = 0;
    goto end_match_4;
next_5:;
    if (!(((call_1 != '\0') == 0))) goto next_6;
    match_1 = 0;
    goto end_match_4;
next_6:;
    exit(1);
end_match_4:;
    int match_2;
    int call_2 = 0;
    if (!(((call_2 != 0) == 1))) goto next_8;
    exit(1);
    match_2 = 0;
    goto end_match_7;
next_8:;
    if (!(((call_2 != 0) == 0))) goto next_9;
    match_2 = 0;
    goto end_match_7;
next_9:;
    exit(1);
end_match_7:;
    int match_3;
    int call_3 = ((int)'a');
    if (!((((call_3 - 97) != 0) == 1))) goto next_11;
    exit(1);
    match_3 = 0;
    goto end_match_10;
next_11:;
    if (!((((call_3 - 97) != 0) == 0))) goto next_12;
    match_3 = 0;
    goto end_match_10;
next_12:;
    exit(1);
end_match_10:;
    int match_4;
    int call_4 = str_to_int((struct String){.str = "42", .len = 2});
    if (!((((call_4 - 42) != 0) == 1))) goto next_14;
    exit(1);
    match_4 = 0;
    goto end_match_13;
next_14:;
    if (!((((call_4 - 42) != 0) == 0))) goto next_15;
    match_4 = 0;
    goto end_match_13;
next_15:;
    exit(1);
end_match_13:;
    int match_5;
    int call_5 = str_to_int((struct String){.str = "-1", .len = 2});
    if (!((((call_5 + 1) != 0) == 1))) goto next_17;
    exit(1);
    match_5 = 0;
    goto end_match_16;
next_17:;
    if (!((((call_5 + 1) != 0) == 0))) goto next_18;
    match_5 = 0;
    goto end_match_16;
next_18:;
    exit(1);
end_match_16:;
    return 0;
}
