int main();

int main() {
    int match_;
    char call_ = ((char)97);
    if (!(((call_ != 'a') == 1))) goto next_2;
    exit(1);
    match_ = 0;
    goto end_match_1;
next_2:;
    if (!(((call_ != 'a') == 0))) goto next_3;
    match_ = 0;
    goto end_match_1;
next_3:;
end_match_1:;
    int match_1;
    char call_1 = ((char)0);
    if (!(((call_1 != '\0') == 1))) goto next_5;
    exit(1);
    match_1 = 0;
    goto end_match_4;
next_5:;
    if (!(((call_1 != '\0') == 0))) goto next_6;
    match_1 = 0;
    goto end_match_4;
next_6:;
end_match_4:;
    int match_2;
    int call_2 = 0;
    if (!(((call_2 != 0) == 1))) goto next_8;
    exit(1);
    match_2 = 0;
    goto end_match_7;
next_8:;
    if (!(((call_2 != 0) == 0))) goto next_9;
    match_2 = 0;
    goto end_match_7;
next_9:;
end_match_7:;
    int match_3;
    int call_3 = ((int)'a');
    if (!((((call_3 - 97) != 0) == 1))) goto next_11;
    exit(1);
    match_3 = 0;
    goto end_match_10;
next_11:;
    if (!((((call_3 - 97) != 0) == 0))) goto next_12;
    match_3 = 0;
    goto end_match_10;
next_12:;
end_match_10:;
    int match_4;
    int call_4 = str_to_int((struct String){.str = "42", .len = 2});
    if (!((((call_4 - 42) != 0) == 1))) goto next_14;
    exit(1);
    match_4 = 0;
    goto end_match_13;
next_14:;
    if (!((((call_4 - 42) != 0) == 0))) goto next_15;
    match_4 = 0;
    goto end_match_13;
next_15:;
end_match_13:;
    int match_5;
    int call_5 = str_to_int((struct String){.str = "-1", .len = 2});
    if (!((((call_5 + 1) != 0) == 1))) goto next_17;
    exit(1);
    match_5 = 0;
    goto end_match_16;
next_17:;
    if (!((((call_5 + 1) != 0) == 0))) goto next_18;
    match_5 = 0;
    goto end_match_16;
next_18:;
end_match_16:;
    int match_6;
    struct String call_6 = str_of_int(0);
    if (!(((str_cmp(call_6, (struct String){.str = "0", .len = 1}) != 0) == 1))) goto next_20;
    exit(1);
    match_6 = 0;
    goto end_match_19;
next_20:;
    if (!(((str_cmp(call_6, (struct String){.str = "0", .len = 1}) != 0) == 0))) goto next_21;
    match_6 = 0;
    goto end_match_19;
next_21:;
end_match_19:;
    int match_7;
    struct String call_7 = str_of_int((0 - 97));
    if (!(((str_cmp(call_7, (struct String){.str = "-97", .len = 3}) != 0) == 1))) goto next_23;
    exit(1);
    match_7 = 0;
    goto end_match_22;
next_23:;
    if (!(((str_cmp(call_7, (struct String){.str = "-97", .len = 3}) != 0) == 0))) goto next_24;
    match_7 = 0;
    goto end_match_22;
next_24:;
end_match_22:;
    int match_8;
    struct String call_8 = str_of_char('a');
    if (!(((str_cmp(call_8, (struct String){.str = "a", .len = 1}) != 0) == 1))) goto next_26;
    exit(1);
    match_8 = 0;
    goto end_match_25;
next_26:;
    if (!(((str_cmp(call_8, (struct String){.str = "a", .len = 1}) != 0) == 0))) goto next_27;
    match_8 = 0;
    goto end_match_25;
next_27:;
end_match_25:;
    int match_9;
    struct String call_9 = str_of_char('\0');
    if (!(((str_cmp(call_9, (struct String){.str = "", .len = 0}) != 0) == 1))) goto next_29;
    exit(1);
    match_9 = 0;
    goto end_match_28;
next_29:;
    if (!(((str_cmp(call_9, (struct String){.str = "", .len = 0}) != 0) == 0))) goto next_30;
    match_9 = 0;
    goto end_match_28;
next_30:;
end_match_28:;
    int match_10;
    struct String call_10 = (struct String){.str = "fix", .len = 3};
    if (!(((str_cmp(call_10, (struct String){.str = "fix", .len = 3}) != 0) == 1))) goto next_32;
    exit(1);
    match_10 = 0;
    goto end_match_31;
next_32:;
    if (!(((str_cmp(call_10, (struct String){.str = "fix", .len = 3}) != 0) == 0))) goto next_33;
    match_10 = 0;
    goto end_match_31;
next_33:;
end_match_31:;
    return 0;
}
