#!/bin/sh
# Register the server to xinetd.
#
# WARN: Such toy server MUST NOT be public on the Internet.
#       The config 'only_from' below rejects non-local access.
#
# Prerequisites:
#   - Install and start 'xinetd' daemon.
#     For example on Ubuntu:
#           sudo apt install xinetd
#           sudo systemctl start xinetd

set -eu

NAME='milone_example_httpd'

if test ! -x "$PWD/target/serve"
then
    echo 'ERROR: make first.' >&2
    exit 1
fi

# Put config file.
if test ! -f "/etc/xinetd.d/$NAME"
then
    cat <<END | sudo tee "/etc/xinetd.d/$NAME"
service $NAME
{
    disable         = no
    flags           = REUSE
    log_on_failure  += USERID
    only_from       = 127.0.0.1/24
    per_source      = UNLIMITED
    port            = 8080
    server          = $PWD/target/serve
    env             = DIST_DIR=$PWD/dist
    socket_type     = stream
    type            = UNLISTED
    user            = nobody
    wait            = no
}
END

    systemctl reload xinetd
fi

echo 'INFO: Try visit <http://localhost:8080/index.html>.'
echo 'INFO: To unregister, remove' "/etc/xinetd.d/$NAME" 'and restart xinetd.'
