#!/bin/bash

set -eu

cat <<END | target/serve
GET /Makefile HTTP/1.1
Content-Length: 0

END

cat <<END | target/serve
GET /path/to/not_found HTTP/1.1
Content-Length: 0

END

cat <<END | target/serve
GET /target/../../../README.md HTTP/1.1
Content-Length: 0

END

cat <<END | target/serve
POST /Makefile HTTP/1.1
Content-Length: 0

END
