#!/bin/bash
# Perform integration test for all cases.
# USAGE: integration-all

set -u

MILONE=${1:-'./milone-netcore'}
VERBOSITY=${2:-'-q'}

if test $MILONE = './milone-netcore'
then
    dotnet build --nologo --no-restore MiloneLang
fi

ERR=$(find tests/*/* -type d | xargs -I{} ./integration-test {} "$MILONE" "$VERBOSITY")
if test ! -z "$ERR"
then
    echo '✘ Some test failed: '$ERR >&2
    exit 1
fi
