#!/bin/sh

set -eu

TEST_DIRS=$(find tests/*/* -type d | grep -v -E '(bin|obj)(/|$)')

./milone-netcore compile --pattern $TEST_DIRS >pat_compile_tmp.generated.txt || echo '$?='$?

mv -bf pat_compile_tmp.generated.txt pat_compile.generated.txt
