#!/bin/sh

set -eu

MILONE_RUNTIME="$PWD/runtime"
DIR="$PWD/scripts/region_primitive_checks"
OUT_C="$DIR/region_primitive_checks.c"

./milone-netcore -q "$DIR" >$OUT_C

(
    cd "$DIR"
    gcc -std=c11 -I "$MILONE_RUNTIME" "$MILONE_RUNTIME/milone.c" -g -fsanitize=undefined,address,leak "$OUT_C"
    ./a.out || echo '$?='$?
    echo OK
)
