#!/bin/sh

set -eu

MILONE_INCLUDE="$PWD/boot/runtime"
DIR="$PWD/boot/scripts/region_primitive_checks"

./milone-netcore -q "$DIR" >"$DIR/region_primitive_checks.c"

(
    cd "$DIR"
    gcc -std=c11 -I "$MILONE_INCLUDE" -g -fsanitize=undefined,address,leak region_primitive_checks.c
    ./a.out || echo '$?='$?
)
