#!/bin/bash

set -eux

CFLAGS='-std=c11 -O2 -I boot/runtime -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label'
GEN2_C='milone_gen2.generated.c'
GEN3_C='milone_gen3.generated.c'

# Build gen2.
./milone-netcore --profile boot/MiloneLang >$GEN2_C

gcc $CFLAGS $GEN2_C -o milone

# Test gen2.
./integration-all ./milone-native -q

# Build gen3.
./milone-native --profile boot/MiloneLang >$GEN3_C

# Check if the gen2 and gen3 are equal.
if diff -q $GEN2_C $GEN3_C
then
    echo '✔ ok'
else
    echo '✘ FAILED'
    exit 1
fi
