#!/bin/bash
# USAGE: test-new features/lambda

set -eu

CATEGORY=$(dirname "$1")
NAME=$(basename "$1")

if test "$CATEGORY" = "." || test "$NAME" = ""
then
    echo 'Invalid arguments.'
    exit 1
fi

if test -d "tests/$CATEGORY/$NAME"
then
    echo 'Already exists.'
    exit 0
fi

mkdir -p "tests/$CATEGORY/$NAME"
echo -e "module rec $NAME.Program\n\nlet main _ =\n  0" >"tests/$CATEGORY/$NAME/$NAME.fs"

(
    if test $CATEGORY = "errors"
    then
        echo "milone-lang compile error."
    else
        echo '$? = 0'
    fi
) >"tests/$CATEGORY/$NAME/$NAME.out"

code "tests/$CATEGORY/$NAME/$NAME.fs"
