#!/bin/sh

set -eu

APP_DIR=$PWD/sandbox/project-reference-example/App
LIB_DIR=$PWD/sandbox/project-reference-example/Lib
APP_C=$APP_DIR/app.generated.c
APP_EXE=$APP_DIR/app.generated.exe

./milone-netcore build "$APP_DIR" --reference "$LIB_DIR" >$APP_C
gcc -std=c11 -O2 -I "$PWD/runtime" "$APP_C" -o $APP_EXE
$APP_EXE
echo OK
