#!/bin/sh
# Delete milone-lang tool-chains from local.

set -eu

BIN_DIR="$HOME/bin"
MILONE_HOME="$HOME/.milone"

# ------------------------------------------------
# Check
# ------------------------------------------------

if test ! -f "$MILONE_HOME/version"
then
    echo 'uninstall: milone-lang is not installed yet.'
    exit 0
fi

VERSION=$(cat $MILONE_HOME/version)

# ------------------------------------------------
# Process
# ------------------------------------------------

echo "uninstall: milone-lang v$VERSION is currently installed."

test -f "$BIN_DIR/milone" && rm "$BIN_DIR/milone"
test -f "$BIN_DIR/milone_dotnet" && rm "$BIN_DIR/milone_dotnet"
test -d "$MILONE_HOME" && rm -rf "$MILONE_HOME"

echo "uninstall: milone-lang v$VERSION is uninstalled successfully."
