version: "3"

services:
  app:
    build: "."
    entrypoint: ["./ci", "test"]
    volumes:
      - ".:/mnt/milone-lang/boot"
      - "app_core_bin:/mnt/milone-lang/boot/MiloneLang/bin"
      - "app_core_obj:/mnt/milone-lang/boot/MiloneLang/obj"
      - "app_tests_bin:/mnt/milone-lang/boot/MiloneLang.Tests/bin"
      - "app_tests_obj:/mnt/milone-lang/boot/MiloneLang.Tests/obj"

volumes:
  app_core_bin:
  app_core_obj:
  app_tests_bin:
  app_tests_obj:
