#!/bin/bash
# Perform single case integration test.
# USAGE: integration-test name milone verbosity

set -u

# Ignore temporary directories.
if [[ $1 =~ /(bin|obj)(/|$) ]]
then
    exit 0
fi

CFLAGS='-std=c11 -I runtime -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label -O1'

NAME=$(basename $1)
MILONE=${2:-'./milone_netcore'}
VERBOSITY=${3:-'-q'}

if [[ -z $1 ]]
then
    echo "Unknown test case '$NAME'." >&2
    exit 1
fi

DIR=$(find tests/*/$NAME -type d | head -n 1)
TEST_SRC="$DIR/$NAME.fs"
TEST_OUTX="$DIR/$NAME.out"
TEST_C="$DIR/~$NAME.c"
TEST_EXE="$DIR/~$NAME"
TEST_OUTA="$DIR/~$NAME.out"

if [[ ! -f $TEST_SRC || ! -f $TEST_OUTX ]]
then
    echo "Missing '$TEST_SRC' or '$TEST_OUTX'" >&2
    exit 0
fi

echo -n "$NAME..." >&2

# Build with milone-lang compiler.
MILONE_CMD="$MILONE $VERBOSITY $DIR"

if [[ $VERBOSITY = '-v' ]]
then
    echo "+ $MILONE_CMD" >&2
fi

$MILONE_CMD >$TEST_C
if [[ $? != 0 ]]
then
    echo 'milone-lang compile error.' >$TEST_OUTA
else
    # Build with C compiler.
    CC_CMD="gcc $CFLAGS $TEST_C -o $TEST_EXE"

    if [[ $VERBOSITY = '-v' ]]
    then
        echo "+ $CC_CMD" >&2
    fi

    $CC_CMD
    if [[ $? != 0 ]]
    then
        echo 'gcc compile error.' >$TEST_OUTA
    else
        # Execute the binary.
        if [[ $VERBOSITY = '-v' ]]
        then
            echo "+ $TEST_EXE" >&2
        fi

        $TEST_EXE >$TEST_OUTA
        echo '$? = '$? >>$TEST_OUTA
    fi
fi

# Verify the result.
if diff -q $TEST_OUTA $TEST_OUTX
then
    echo "✔ ok" >&2
else
    echo "✘ FAILED" >&2
    echo $NAME
fi
