#!/bin/bash

set -eu

name=$(basename "$1" .milone)
echo $name

app="./tmp/$name"
out="./tmp/$name.out"
exp="./tests/targets/$name.out"
./trans "$name" 2>/dev/null

set +e
$app >$out
echo '$? = '$? >>$out
diff -q $out $exp || {
    >&2 echo "FAILED $name"
}
set -e
