#!/bin/bash

# Run milone code and verify stdout and exit code.
# SAMPLE: ./integ-try ./tests/src/hello.milone
# SAMPLE: ./integ-try hello

set -eu

name=$(basename "$1" .milone)
echo -n "$name ... "

app="./tmp/$name"
out="./tmp/$name.out"
exp="./tests/targets/$name.out"
./trans "$name" 2>/dev/null

set +e
$app >$out
echo '$? = '$? >>$out
diff -q $out $exp >/dev/null && {
    >&2 echo "✔ ok"
} || {
    >&2 echo "✘ FAILED"
}
set -e
