#!/bin/bash

set -eux

OUT=tests/examples/MiloneLang/MiloneLang.out

dotnet build MiloneLang -c Release
dotnet run -p MiloneLang -c Release -- --self >$OUT
echo '$?' = $? >>$OUT

./task integ MiloneLang
