#!/bin/bash

set -eux

CFLAGS='-std=c11 -I runtime -Wall -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label -O3'
GEN2_C='./~milone_gen2.c'
GEN3_C='./~milone_gen3.c'

# Build gen2.
./milone_netcore --profile MiloneLang >$GEN2_C

gcc $CFLAGS $GEN2_C -o milone

# Test gen2.
./integration-all ./milone -q

# Build gen3.
MILONE_HOME=$PWD/.. ./milone --profile MiloneLang >$GEN3_C

# Check if the gen2 and gen3 are equal.
if diff -q $GEN2_C $GEN3_C
then
    echo '✔ ok'
else
    echo '✘ FAILED'
    exit 1
fi
