#!/bin/bash

cp MiloneLang/Compatible.fs tests/examples/MiloneLang/Compatible.fs
cp MiloneLang/Types.fs tests/examples/MiloneLang/Types.fs
cp MiloneLang/Records.fs tests/examples/MiloneLang/Records.fs
cp MiloneLang/Helpers.fs tests/examples/MiloneLang/Helpers.fs
cp MiloneLang/Lexing.fs tests/examples/MiloneLang/Lexing.fs
cp MiloneLang/Parsing.fs tests/examples/MiloneLang/Parsing.fs
cp MiloneLang/AstToHir.fs tests/examples/MiloneLang/AstToHir.fs
cp MiloneLang/Bundling.fs tests/examples/MiloneLang/Bundling.fs
cp MiloneLang/NameRes.fs tests/examples/MiloneLang/NameRes.fs
cp MiloneLang/Typing.fs tests/examples/MiloneLang/Typing.fs
cp MiloneLang/MainHoist.fs tests/examples/MiloneLang/MainHoist.fs
cp MiloneLang/ClosureConversion.fs tests/examples/MiloneLang/ClosureConversion.fs
cp MiloneLang/EtaExpansion.fs tests/examples/MiloneLang/EtaExpansion.fs
cp MiloneLang/Hoist.fs tests/examples/MiloneLang/Hoist.fs
cp MiloneLang/Monomorphizing.fs tests/examples/MiloneLang/Monomorphizing.fs
cp MiloneLang/Mir.fs tests/examples/MiloneLang/Mir.fs
cp MiloneLang/CIrGen.fs tests/examples/MiloneLang/CIrGen.fs
cp MiloneLang/CPrinting.fs tests/examples/MiloneLang/CPrinting.fs

(cd tests/examples/MiloneLang; dotnet build)
