/// ## Records
///
/// Generated by scripts/RecordGen from `Records.yml`.
/// Run `./records` to regenerate.
///
/// Defines some types as synonym of tuple with getter/setter functions
/// because record types are unimplemented in milone-lang.
module rec MiloneLang.Records

open MiloneLang.Types

type ExampleCtx =
  (
    Serial
    * Map<VarSerial, VarDef>
    * Map<TySerial, TyDef>
  )

let exampleCtxGetSerial ((serial, _, _): ExampleCtx) =
  serial

let exampleCtxGetVars ((_, vars, _): ExampleCtx) =
  vars

let exampleCtxGetTys ((_, _, tys): ExampleCtx) =
  tys

let exampleCtxWithSerial serial ((_, vars, tys): ExampleCtx): ExampleCtx =
  serial, vars, tys

let exampleCtxWithVars vars ((serial, _, tys): ExampleCtx): ExampleCtx =
  serial, vars, tys

let exampleCtxWithTys tys ((serial, vars, _): ExampleCtx): ExampleCtx =
  serial, vars, tys

type AnotherCtx =
  (
    Serial
    * MStmt list
  )

let anotherCtxGetSerial ((serial, _): AnotherCtx) =
  serial

let anotherCtxGetStmts ((_, stmts): AnotherCtx) =
  stmts

let anotherCtxWithSerial serial ((_, stmts): AnotherCtx): AnotherCtx =
  serial, stmts

let anotherCtxWithStmts stmts ((serial, _): AnotherCtx): AnotherCtx =
  serial, stmts
