#!/bin/sh
# Download and compile pdjson (json parser) from <https://github.com/skeeto/pdjson>.

set -eu

CC=${CC:-gcc}

mkdir -p vendor

(
    cd vendor
    wget -q 'https://github.com/skeeto/pdjson/archive/67108d883061043e55d0fb13961ac1b6fc8a485c.tar.gz' -O - | tar xz
    mv pdjson-67108d883061043e55d0fb13961ac1b6fc8a485c pdjson
    
    cd pdjson
    $CC -O2 -c pdjson.c
)
