int main() {
    struct String str_3 = (struct String){.str = "Hello, John!", .len = 12};
    int if_4;
    struct String slice_5 = str_slice(str_3, 0, 4);
    if (!((str_cmp(slice_5, (struct String){.str = "Hello", .len = 5}) != 0))) goto else_1;
    exit(1);
    if_4 = 0;
    goto end_if_2;
else_1:;
    if_4 = 0;
end_if_2:;
    int if_6;
    struct String slice_7 = str_slice(str_3, 7, 10);
    if (!((str_cmp(slice_7, (struct String){.str = "John", .len = 4}) != 0))) goto else_3;
    exit(2);
    if_6 = 0;
    goto end_if_4;
else_3:;
    if_6 = 0;
end_if_4:;
    int if_8;
    struct String slice_9 = str_slice(str_3, 11, 11);
    if (!((str_cmp(slice_9, (struct String){.str = "!", .len = 1}) != 0))) goto else_5;
    exit(3);
    if_8 = 0;
    goto end_if_6;
else_5:;
    if_8 = 0;
end_if_6:;
    return 0;
}
