#!/bin/sh
# USAGE: scripts/project-reference-example/test

set -eu

PROJECT_DIR="$PWD/scripts/project-reference-example/App"
MILONE_HOME=${MILONE_HOME:-$PWD}
MILONE=${MILONE:-bin/milone-latest}

MILONE_HOME=$MILONE_HOME $MILONE run "$PROJECT_DIR" | \
    diff - "$PROJECT_DIR/../app.output" && \
    echo OK
