# USAGE: docker-compose -f scripts/docker-compose.dev.yml up

version: "3"

services:
  app:
    build:
      context: "scripts"
      dockerfile: "scripts/dockerfile-dev"
    volumes:
      - ".:/mnt/milone-lang"

      # These mounts prevent the docker from sync-ing.
      - "milone_lang_bin:/mnt/milone-lang/MiloneLang/bin"
      - "milone_lang_obj:/mnt/milone-lang/MiloneLang/obj"
      - "milone_lsp_bin:/mnt/milone-lang/milone_lsp/bin"
      - "milone_lsp_obj:/mnt/milone-lang/milone_lsp/obj"
      - "milone_std_bin:/mnt/milone-lang/milone_libs/MiloneStd/bin"
      - "milone_std_obj:/mnt/milone-lang/milone_libs/MiloneStd/obj"
      - "milone_tests_bin:/mnt/milone-lang/MiloneTests/bin"
      - "milone_tests_obj:/mnt/milone-lang/MiloneTests/obj"

volumes:
  milone_lang_bin:
  milone_lang_obj:
  milone_lsp_bin:
  milone_lsp_obj:
  milone_std_bin:
  milone_std_obj:
  milone_tests_bin:
  milone_tests_obj:
