#!/bin/sh

set -eu

CC=${CC:-gcc}
CXX=${CXX:-g++}
MILONE_HOME=${MILONE_HOME:-$HOME/.milone}
TARGET=$PWD/../target/Parallel

TBB_INCLUDE=/usr/local/include/tbb/
CXX_FLAGS="\
    -std=c++11 \
    -g \
    -I$MILONE_HOME/runtime \
    -I$TBB_INCLUDE \
"

milone build --target-dir "$TARGET" $PWD

$CXX $CXX_FLAGS -c lib_parallel.cpp -o $TARGET/lib_parallel.o
$CXX $CXX_FLAGS -c milone_multithread_allocator.cpp -o $TARGET/milone_multithread_allocator.o

$CC -I$MILONE_HOME/runtime -g -c milone_multithread_runtime.c -o $TARGET/milone_multithread_runtime.o

$CXX -I$MILONE_HOME/runtime \
    -g \
    $TARGET/lib_parallel.o \
    $TARGET/milone_multithread_allocator.o \
    $TARGET/milone_multithread_runtime.o \
    $(find "$TARGET" -name '*.c' | xargs -I{} echo '-x c {}') \
    -o $TARGET/parallel \
    -ldl -ltbb
