int main() {
    Box tuple_12 = {.t = malloc(2 * sizeof(Box))};
    tuple_12.t[0] = (Box){.i = 1};
    tuple_12.t[1] = (Box){.s = "snd"};
    Box a_2 = tuple_12;
    int op_13 = (1 * a_2.t[0].i);
    int x_3 = op_13;
    printf("%d\n", x_3);
    int call_14 = 0;
    Box tuple_15 = {.t = malloc(2 * sizeof(Box))};
    tuple_15.t[0] = (Box){.s = "fst"};
    tuple_15.t[1] = (Box){.i = 2};
    Box b_4 = tuple_15;
    char* y_5 = b_4.t[0].s;
    printf("%s\n", y_5);
    int call_16 = 0;
    Box tuple_17 = {.t = malloc(2 * sizeof(Box))};
    tuple_17.t[0] = (Box){.s = "z"};
    tuple_17.t[1] = (Box){.s = "w"};
    char* z_6 = tuple_17.t[0].s;
    char* w_7 = tuple_17.t[1].s;
    printf("z=%s\n", z_6);
    int call_18 = 0;
    printf("w=%s\n", w_7);
    int call_19 = 0;
    Box tuple_21 = {.t = malloc(2 * sizeof(Box))};
    tuple_21.t[0] = (Box){.s = "p"};
    tuple_21.t[1] = (Box){.s = "q"};
    Box tuple_20 = {.t = malloc(2 * sizeof(Box))};
    tuple_20.t[0] = tuple_21;
    tuple_20.t[1] = (Box){.s = "r"};
    char* p_8 = tuple_20.t[0].t[0].s;
    char* q_9 = tuple_20.t[0].t[1].s;
    char* r_10 = tuple_20.t[1].s;
    printf("p=%s\n", p_8);
    int call_22 = 0;
    return 0;
}
