int main() {
    Box tuple_12 = {.t = malloc(2 * sizeof(Box))};
    tuple_12.t[0] = (Box){.i = 1};
    tuple_12.t[1] = (Box){.s = "snd"};
    Box a_2 = tuple_12;
    int x_3 = (1 * a_2.t[0].i);
    printf("%d\n", x_3);
    int call_13 = 0;
    Box tuple_14 = {.t = malloc(2 * sizeof(Box))};
    tuple_14.t[0] = (Box){.s = "fst"};
    tuple_14.t[1] = (Box){.i = 2};
    Box b_4 = tuple_14;
    char* y_5 = b_4.t[0].s;
    printf("%s\n", y_5);
    int call_15 = 0;
    Box tuple_16 = {.t = malloc(2 * sizeof(Box))};
    tuple_16.t[0] = (Box){.s = "z"};
    tuple_16.t[1] = (Box){.s = "w"};
    char* z_6 = tuple_16.t[0].s;
    char* w_7 = tuple_16.t[1].s;
    printf("z=%s\n", z_6);
    int call_17 = 0;
    printf("w=%s\n", w_7);
    int call_18 = 0;
    Box tuple_20 = {.t = malloc(2 * sizeof(Box))};
    tuple_20.t[0] = (Box){.s = "p"};
    tuple_20.t[1] = (Box){.s = "q"};
    Box tuple_19 = {.t = malloc(2 * sizeof(Box))};
    tuple_19.t[0] = tuple_20;
    tuple_19.t[1] = (Box){.s = "r"};
    char* p_8 = tuple_19.t[0].t[0].s;
    char* q_9 = tuple_19.t[0].t[1].s;
    char* r_10 = tuple_19.t[1].s;
    printf("p=%s\n", p_8);
    int call_21 = 0;
    return 0;
}
