#!/bin/sh

set -eu

CC=${CC:-gcc}
MILONE_HOME=${MILONE_HOME:-$HOME/.milone}
TARGET=$PWD/../target/CmdJsonGet

milone build --target-dir "$TARGET" $PWD

$CC -std=gnu11 \
    -I$MILONE_HOME/runtime \
    ../vendor/pdjson/pdjson.o \
    $MILONE_HOME/runtime/milone.c \
    ../LibJson/lib_json_runtime.c \
    cmd_json_get_runtime.c \
    $(find "$TARGET" -name '*.c') \
    -o $TARGET/json_get
