/// ## Records
///
/// Generated by scripts/RecordGen from `Records.yml`.
/// Run `./records` to regenerate.
///
/// Defines some types as synonym of tuple with getter/setter functions
/// because record types are unimplemented in milone-lang.
module rec MiloneLang.Records

open MiloneLang.Types

type CliHost =
  | CliHost
    of string list
      * string
      * (unit -> Profiler)
      * (string -> Profiler -> unit)
      * (string -> string option)

let cliHostGetArgs (CliHost (args, _, _, _, _)) =
  args

let cliHostGetMiloneHome (CliHost (_, miloneHome, _, _, _)) =
  miloneHome

let cliHostGetProfileInit (CliHost (_, _, profileInit, _, _)) =
  profileInit

let cliHostGetProfileLog (CliHost (_, _, _, profileLog, _)) =
  profileLog

let cliHostGetFileReadAllText (CliHost (_, _, _, _, fileReadAllText)) =
  fileReadAllText

let cliHostWithArgs args (CliHost (_, miloneHome, profileInit, profileLog, fileReadAllText)): CliHost =
  CliHost (args, miloneHome, profileInit, profileLog, fileReadAllText)

let cliHostWithMiloneHome miloneHome (CliHost (args, _, profileInit, profileLog, fileReadAllText)): CliHost =
  CliHost (args, miloneHome, profileInit, profileLog, fileReadAllText)

let cliHostWithProfileInit profileInit (CliHost (args, miloneHome, _, profileLog, fileReadAllText)): CliHost =
  CliHost (args, miloneHome, profileInit, profileLog, fileReadAllText)

let cliHostWithProfileLog profileLog (CliHost (args, miloneHome, profileInit, _, fileReadAllText)): CliHost =
  CliHost (args, miloneHome, profileInit, profileLog, fileReadAllText)

let cliHostWithFileReadAllText fileReadAllText (CliHost (args, miloneHome, profileInit, profileLog, _)): CliHost =
  CliHost (args, miloneHome, profileInit, profileLog, fileReadAllText)
