#!/bin/bash

set -eu

MILONE_LANG_DIR="$(dirname $PWD)/MiloneLang"

dotnet build

CONTENTS=$(cat ${MILONE_LANG_DIR}/MiloneLang.milone | ./json-encode)

{
./req <<END
{"method": "initialize", "id": 1, "params": {
    "rootUri": "file://${MILONE_LANG_DIR}"
}}
END

./req <<END
{"method": "textDocument/didOpen", "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone",
        "languageId": "milone",
        "version": 1,
        "text": $CONTENTS
    }
}}
END

./req <<END
{"method": "textDocument/didChange", "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone",
        "version": 2
    },
    "contentChanges": [
        {
            "text": $CONTENTS
        }
    ]
}}
END

./req <<END
{"method": "textDocument/didChange", "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone",
        "version": 3
    },
    "contentChanges": [
        {
            "text": $CONTENTS
        }
    ]
}}
END

sleep 3s

./req <<END
{"method": "shutdown", "id": 1000000000}
END

./req <<END
{"method": "exit"}
END
} | MILONE_HOME="$(dirname $PWD)" dotnet run
