#!/bin/bash

set -eu

MILONE_LANG_DIR="$(dirname $PWD)/MiloneLang"

{
./req <<END
{"method": "initialize", "id": 1, "params": {
    "rootUri": "file:///${MILONE_LANG_DIR}"
}}
END

./req <<END
{"method": "textDocument/didOpen", "params": {
    "textDocument": {
        "uri": "file:///${MILONE_LANG_DIR}/MiloneLang.milone",
        "languageId": "milone",
        "version": 1,
        "text": $(cat ${MILONE_LANG_DIR}/MiloneLang.milone | ./json-encode)
    }
}}
END

./req <<END
{"method": "shutdown", "id": 1000000000}
END

./req <<END
{"method": "exit"}
END
} | dotnet run
