#!/bin/sh

set -eu

CC=${CC:-gcc}
MILONE_HOME=${MILONE_HOME:-$HOME/.milone}
TARGET=$PWD/../target/CmdSqliteTodo

milone compile --target-dir "$TARGET" $PWD

$CC -std=gnu11 \
    -I$MILONE_HOME/runtime \
    ../vendor/sqlite3/sqlite3.o \
    $MILONE_HOME/runtime/milone.c \
    $MILONE_HOME/runtime/milone_platform.c \
    ../LibSqlite3/lib_sqlite3_runtime.c \
    $(find "$TARGET" -name '*.c') \
    -o $TARGET/todo \
    -ldl -lpthread
