#!/bin/sh

set -eu

MILONE_HOME="${MILONE_HOME:-$HOME/.milone}"

gcc -std=gnu11 -g \
    -fsanitize=undefined \
    -Wall \
    -Wextra \
    -Wno-unused-but-set-parameter \
    -Wno-unused-but-set-variable \
    -Wno-unused-label \
    -Wno-unused-parameter \
    -Wno-unused-variable \
    -I "$MILONE_HOME/runtime" \
    "$MILONE_HOME/runtime/milone.c" \
    vendor/pdjson/pdjson.c \
    vendor/sqlite3/sqlite3.o \
    milone_lsp_server_runtime.c \
    target/milone_lsp_server.c \
    -o target/milone_lsp_server \
    -lpthread -ldl
