#!/bin/sh

# FIXME: update

set -eu

CC=${CC:-gcc}
MILONE_HOME=${MILONE_HOME:-$HOME/.milone}
TARGET="$PWD/target"

mkdir -p $TARGET

{
    echo '#include "../LibSpan/lib_span_runtime.h"'
    milone compile $PWD
} >$TARGET/lib_span_tests.c

$CC -std=gnu11 -fsanitize=address,undefined \
    -I$MILONE_HOME/src/libmilonert \
    $MILONE_HOME/src/libmilonert/milone.c \
    $MILONE_HOME/src/libmilonert/milone_platform.c \
    ../LibSpan/lib_span_runtime.c \
    $TARGET/lib_span_tests.c \
    -o $TARGET/lib_span_tests
