#!/bin/sh
# Build milone binary without using ninja.

set -eu

CC=${CC:-gcc}

# ------------------------------------------------
# Check
# ------------------------------------------------

dotnet --version >/dev/null
$CC --version >/dev/null

# ------------------------------------------------
# Process
# ------------------------------------------------

mkdir -p target/gen2

MILONE_HOME=$PWD \
    dotnet run -p MiloneLang -- \
    compile --quiet --target-dir target/gen2 \
    MiloneLang

MILONE_HOME=$PWD \
INPUTS='target/gen2/MiloneLang.c' \
OUTPUT='target/milone' \
    scripts/build-with-cc
