#!/bin/sh
# Build a milone-lang project (output C code) to executable with C compiler.

# ENV:
#   MILONE_HOME: defaults to $HOME/.milone
#   CC: C compiler, defaults to 'gcc'.
#   CFLAGS: defaults to -O2
#   INPUTS: list of C files
#   OUTPUT: output file name, defaults to 'a.out'.

set -eu

MILONE_HOME=${MILONE_HOME:-"$HOME/.milone"}
CC=${CC:-gcc}
CFLAGS=${CFLAGS:-'-O2'}

CFLAGS_ALL="-std=c11 \
    $CFLAGS \
    -Wall \
    -Wextra \
    -Wpedantic \
    -Wno-parentheses-equality \
    -Wno-pointer-to-int-cast \
    -Wno-unknown-warning-option \
    -Wno-unused-but-set-variable \
    -Wno-unused-const-variable \
    -Wno-unused-label \
    -Wno-unused-parameter \
    -Wno-unused-variable \
    -I$MILONE_HOME/runtime \
    $MILONE_HOME/runtime/milone.c \
    "

$CC $CFLAGS_ALL $INPUTS -o ${OUTPUT:-'a.out'}
