#!/bin/bash
# Build the milone-lang compiler on Windows + Git Bash.
#
# Prerequisites:
#   - dotnet
#   - MSBuild.exe in PATH
#
# USAGE: scripts/build-milone-windows

set -eux

dotnet --version >/dev/null
MSBuild.exe -version >/dev/null

mkdir -p target/windows

MILONE_HOME=$PWD dotnet run -p MiloneLang -- compile MiloneLang >target/milone_gen2.c

# HACK: MSVC seems to handle minimum int literal incorrectly.
sed -i 's;-2147483648;0x80000000;' target/milone_gen2.c

MSBuild.exe 'scripts/milone-lang-win10-msvc/milone-lang-win10-msvc.sln' '-p:Configuration=Release;Platform=x64'
