#!/bin/sh
# Build milone binary without using ninja.

set -eu

CC=${CC:-gcc}

# ------------------------------------------------
# Check
# ------------------------------------------------

dotnet --version >/dev/null
$CC --version >/dev/null

# ------------------------------------------------
# Process
# ------------------------------------------------

mkdir -p target

MILONE_HOME=$PWD \
    dotnet run -p MiloneLang -- \
    compile --quiet MiloneLang \
    >'target/milone_gen2.c'

MILONE_HOME=$PWD \
INPUTS='target/milone_gen2.c' \
OUTPUT='target/milone' \
    scripts/build-with-cc
