#!/bin/sh
# Build milone binary.

set -eu

CC=${CC:-gcc}

# ------------------------------------------------
# Check
# ------------------------------------------------

dotnet --version >/dev/null
$CC --version >/dev/null

# ------------------------------------------------
# Process
# ------------------------------------------------

MILONE_HOME=$PWD PATH=$PWD/bin:$PATH \
    dotnet run -p src/MiloneCli -- \
    run --target-dir target/gen2 \
    src/MiloneCli -- --version

cp -f target/gen2/MiloneCli.exe target/milone
