#!/bin/sh
# USAGE: scripts/check_region_primitive

set -eu

CC=${CC:-gcc}

MILONE_RUNTIME="$PWD/runtime"
DIR="$PWD/scripts/region_primitive_checks"
OUT_C="$DIR/region_primitive_checks.c"

milone -q "$DIR" >$OUT_C

(
    cd "$DIR"
    $CC -std=c11 -g \
        -fsanitize=address,leak,undefined \
        -I$MILONE_RUNTIME \
        "$MILONE_RUNTIME/milone.c" \
        "$OUT_C"
    ./a.out || echo '$?='$?
    echo OK
)
