#!/bin/sh
# See also: https://github.com/ninja-build/ninja

set -eu

URL='https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip'

mkdir -p bin

if test -x bin/ninja
then
    echo 'trace: bin/ninja is already installed.' >&2
    exit
fi

dotnet fsi scripts/DownloadZip.fsx "$URL" -o bin
chmod +x bin/ninja
