#!/bin/sh
# Parse milone-lang code to see syntax errors.
# No output if no error by default.
#
# USAGE: scripts/parse-self

set -eu

# With -q, errors are only emitted.
# With -v, all syntax is emitted (too long to see).
milone parse -q MiloneLang
