#!/bin/sh

set -eu

MILONE_HOME="$(dirname "$0")/.."
# MILONE="$MILONE_HOME/target/MiloneCli/x86_64-unknown-linux-gnu-release/MiloneCli"
MILONE=${MILONE:-milone}

MILONE_HOME=$MILONE_HOME $MILONE run "$MILONE_HOME/src/Std"
