#!/bin/sh
# USAGE: ./scripts/try-project-reference

set -eu

APP_DIR="$PWD/scripts/project-reference-example/App"
APP_C="$APP_DIR/app.generated.c"
APP_EXE="$APP_DIR/app.generated.exe"

./milone-dotnet build "$APP_DIR" >$APP_C
gcc -std=c11 -O2 -I "$PWD/runtime" "$PWD/runtime/milone.c" "$APP_C" -o "$APP_EXE"
$APP_EXE
echo OK
