#include "milone.h"

int main();

int main() {
    int match_;
    match_ = 0;
    goto end_match_1;
next_2:;
end_match_1:;
    int match_1;
    if (!((1 == 0))) goto next_4;
    milone_assert(0, 5, 13);
    int call_ = 0;
    match_1 = 0;
    goto end_match_3;
next_4:;
    if (!((1 == 1))) goto next_5;
    match_1 = 0;
    goto end_match_3;
next_5:;
    milone_assert(0, 7, 9);
    int call_1 = 0;
    match_1 = 0;
    goto end_match_3;
next_6:;
end_match_3:;
    int match_2;
    if (!((1 == 0))) goto next_8;
    milone_assert(0, 10, 9);
    int call_2 = 0;
    match_2 = 0;
    goto end_match_7;
next_8:;
    if (!((1 == 1))) goto next_9;
    match_2 = 0;
    goto end_match_7;
next_9:;
    milone_assert(0, 12, 9);
    int call_3 = 0;
    match_2 = 0;
    goto end_match_7;
next_10:;
end_match_7:;
    int match_3;
    if (!(('a' == 'A'))) goto next_12;
    milone_assert(0, 15, 11);
    int call_4 = 0;
    match_3 = 0;
    goto end_match_11;
next_12:;
    if (!(('a' == 'a'))) goto next_13;
    match_3 = 0;
    goto end_match_11;
next_13:;
    milone_assert(0, 17, 9);
    int call_5 = 0;
    match_3 = 0;
    goto end_match_11;
next_14:;
end_match_11:;
    int match_4;
    if (!((str_cmp((struct String){.str = "a", .len = 1}, (struct String){.str = "an", .len = 2}) == 0))) goto next_16;
    milone_assert(0, 20, 12);
    int call_6 = 0;
    match_4 = 0;
    goto end_match_15;
next_16:;
    if (!((str_cmp((struct String){.str = "a", .len = 1}, (struct String){.str = "a", .len = 1}) == 0))) goto next_17;
    match_4 = 0;
    goto end_match_15;
next_17:;
    milone_assert(0, 22, 9);
    int call_7 = 0;
    match_4 = 0;
    goto end_match_15;
next_18:;
end_match_15:;
    return 0;
}
