int main();

int main() {
    int x_ = 1;
    int x_1 = 0;
    int match_;
    if (!(((x_1 != 0) == 1))) goto next_2;
    exit(1);
    match_ = 0;
    goto end_match_1;
next_2:;
    if (!(((x_1 != 0) == 0))) goto next_3;
    match_ = 0;
    goto end_match_1;
next_3:;
    exit(1);
end_match_1:;
    int case1_ = 0;
    int x_2 = 0;
    int x_3 = 1;
    int match_1;
    if (!(((x_3 != 1) == 1))) goto next_5;
    exit(1);
    match_1 = 0;
    goto end_match_4;
next_5:;
    if (!(((x_3 != 1) == 0))) goto next_6;
    match_1 = 0;
    goto end_match_4;
next_6:;
    exit(1);
end_match_4:;
    int match_2;
    if (!(((x_2 != 0) == 1))) goto next_8;
    exit(1);
    match_2 = 0;
    goto end_match_7;
next_8:;
    if (!(((x_2 != 0) == 0))) goto next_9;
    match_2 = 0;
    goto end_match_7;
next_9:;
    exit(1);
end_match_7:;
    int case2_ = 0;
    return 0;
}
