#!/bin/sh

set -eu

# Initialize.
if test ! -d /mnt/milone-lang/.git
then
    git clone /mnt/milone-lang-host /mnt/milone-lang
    date --iso=seconds >/root/since
fi

cd /mnt/milone-lang
dotnet restore 2>&1 >/dev/null

while :
do
    SINCE=$(cat /root/since 2>/dev/null || date --iso=seconds)
    date --iso=seconds >/root/since

    git fetch 2>&1 | grep -- '->' || :

    git log --all --no-merges "--since=$SINCE" "--pretty=%H %f" | \
        xargs --no-run-if-empty -L1 sh /etc/on-build-wrap

    echo 'info: Waiting for commits.'
    inotifywait -q /mnt/milone-lang-host/.git/refs/heads -e modify

    while inotifywait -q /mnt/milone-lang-host/.git/refs/heads -e modify --timeout 2; \
        test $? -ne 2
    do :
    done
done
