#!/bin/sh
# Run container for CI.
#
# Uses /tmp/milone-ci .

set -eu

if test "$(basename $PWD)" != 'milone-lang'
then
    echo 'Run in milone-lang directory.'
    exit 1
fi

# MODE='--detach --restart unless-stopped'
MODE='--rm -it'

docker run \
    $MODE \
    --init \
    --mount "type=bind,src=$PWD,destination=/mnt/milone-lang-host,readonly" \
    -v "/tmp/milone-ci/milone-lang:/mnt/milone-lang" \
    -v "/tmp/milone-ci/log:/var/log/build" \
    -v "/tmp/milone-ci/done:/root/done" \
    local/milone-ci \
    # bash
    # sh /etc/docker-entrypoint
