#!/bin/bash

set -eu

MILONE_LANG_DIR="$(dirname $PWD)/MiloneLang"

dotnet build

{
./req <<END
{"method": "initialize", "id": 1, "params": {
    "rootUri": "file://${MILONE_LANG_DIR}"
}}
END

./req <<END
{"method": "textDocument/definition", "id": 2, "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone"
    },
    "position": {
        "line": 48,
        "character": 13
    }
}}
END

./req <<'END'
{"method": "$/cancelRequest", "params": {
    "id": 2
}}
END

./req <<END
{"method": "shutdown", "id": 3}
END

./req <<END
{"method": "exit"}
END
} | MILONE_HOME="$(dirname $PWD)" dotnet run 2>err.generated.txt
