#!/bin/bash

set -eu

MILONE_LANG_DIR="$(dirname $PWD)/MiloneLang"

{
./req <<END
{"method": "initialize", "id": 1, "params": {
    "rootUri": "file://${MILONE_LANG_DIR}"
}}
END

./req <<END
{"method": "textDocument/definition", "id": 2, "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone"
    },
    "position": {
        "line": 48,
        "character": 13
    }
}}
END

./req <<END
{"method": "textDocument/references", "id": 3, "params": {
    "textDocument": {
        "uri": "file://${MILONE_LANG_DIR}/MiloneLang.milone"
    },
    "position": {
        "line": 54,
        "character": 2
    },
    "context": {
        "includeDeclaration": true
    }
}}
END

./req <<END
{"method": "shutdown", "id": 1000000000}
END

./req <<END
{"method": "exit"}
END
} | MILONE_HOME="$(dirname $PWD)" dotnet run 2>err.generated.txt
