#!/bin/sh

set -eu

PROJECT_DIR=$(dirname "$PWD/$0")

(
    cd "$PROJECT_DIR"
    set -x

    milone build "$PROJECT_DIR" -o libsotest.so
    gcc -c app.c -o app.o
    gcc -o app.out libsotest.so app.o
    ./app.out
)
